### ISSUE TITLE
after-build script failure when the parent folder's name contains a '+'

### ISSUE THREAD

**Issue by avys1** [szabonorbert/zorro-project-template#1]
When the parent folder's name contains a '+' (like 'MyStrategy+') the the after-build script fails, and, ad a result, the build of the solution fails. Thus, you cannot maintain the Zorro's naming convention of ending .cpp strategies with a '+'.

**Comment by avys1** [comment]
Thanks.BTW - it is a good place to thank you about sharing this project. Really got me on the way after 4 hours of frustration trying to figure out myself what to do and battling with MS-Visual Studio (the worst development environment of earth, at least IMO).Avy
    On Monday, October 7, 2024 at 03:57:44 PM GMT+3, szabonorbert ***@***.***> wrote:  
 
 


Closed #1 as completed via #2.

**Comment by szabonorbert** [comment]
You are welcome, I'm glad it helps. I feel your struggle, I also switched IDE for Zorro projects, thankfully we can use VSCode:
https://github.com/szabonorbert/zorro-vscode-template
