### ISSUE TITLE
Hi, Can you make Rithmic API for Zorro trader > C Lite / C / C++ ? https://zorro-project.com/manual/toc.php 

### ISSUE THREAD

**Issue by LA-TRDR** [szabonorbert/zorro-project-template#3]
Hi, Can you make Rithmic API for Zorro trader > C Lite / C / C++ ? https://zorro-project.com/manual/toc.php , Thank You, Lauri

**Comment by szabonorbert** [comment]
Hi,

Maybe yes, but I am far from being a Zorro expert and I am also not looking for dev contracts.
I would try [here](https://zorro-project.com/development.php) or [here](https://www.vitaltrades.com/).
